# Generated by Django 4.0.6 on 2022-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('moderada', 'Moderada'), ('a fazer', 'A fazer')], default='importante', max_length=25),
        ),
    ]
