# Generated by Django 4.0.6 on 2022-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_alter_tarefa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default=False, max_length=24),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
