# Generated by Django 4.0.6 on 2022-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_tarefa_titulo_alter_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='Sem Título', max_length=24),
        ),
    ]
