# Generated by Django 4.0.6 on 2022-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0005_alter_tarefa_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('moderada', 'Moderada'), ('a fazer', 'A fazer')], 
                                                default='---------', max_length=25),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
