# Generated by Django 4.0.6 on 2022-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0007_alter_tarefa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[(None, '---------'), ('urgente', 'Urgente'), ('moderada', 'Moderada'), ('a fazer', 'A fazer')], default='---------', max_length=25),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(),
        ),
    ]
