# Generated by Django 4.0.6 on 2022-07-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_alter_tarefa_titulo'),
        ('lista', '0009_alter_tarefa_descricao'),
    ]

    operations = [
    ]
