# Generated by Django 4.0.6 on 2022-07-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0010_merge_20220725_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
